spring.jpa.hibernate.ddl-auto: create-drop
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:C:/tmp/customer
    username: sa
    password: 
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: validate
security:
  basic:
    enabled: false